"""updated user table

Revision ID: dd3c7ab52e9b
Revises: bf15f6b384f3
Create Date: 2018-02-20 21:19:40.765625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3c7ab52e9b'
down_revision = 'bf15f6b384f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pickup_address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('pickup_city', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('pickup_state', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_user_pickup_address'), 'user', ['pickup_address'], unique=False)
    op.create_index(op.f('ix_user_pickup_city'), 'user', ['pickup_city'], unique=False)
    op.create_index(op.f('ix_user_pickup_state'), 'user', ['pickup_state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pickup_state'), table_name='user')
    op.drop_index(op.f('ix_user_pickup_city'), table_name='user')
    op.drop_index(op.f('ix_user_pickup_address'), table_name='user')
    op.drop_column('user', 'pickup_state')
    op.drop_column('user', 'pickup_city')
    op.drop_column('user', 'pickup_address')
    # ### end Alembic commands ###
